### PR TITLE
Allow using the crate with custom target JSON specs

### PR DESCRIPTION
**Pull request by jonas-schievink**
This should fix https://github.com/rust-embedded/cortex-m-rt/issues/145 (cc @thejpster)

### CODE REVIEW

**Comment by adamgreig** [comment]
Idea seems good but this breaks when target is `thumbv8m.base-none-eabi` and similar.

**Comment by jonas-schievink** [comment]
`Path::new("thumbv8m.base-none-eabi.json").file_stem().unwrap().to_str().unwrap()` results in `thumbv8m.base-none-eabi`, so this should work fine. `file_stem` only strips preceding directories and the last suffix.

**Comment by adamgreig** [comment]
Won't it also run for just "--target thumbv8m.base-none-eabi", without a JSON spec, though?

**Comment by jonas-schievink** [comment]
Oh, right, that's a problem.

**Review by adamgreig — APPROVED** [review]
Thanks!

bors merge

**Review by adamgreig — APPROVED** [review]
bors merge

**Pull request merged**
