### PR TITLE
v0.6.2

### PR DESCRIPTION
**Pull request by japaric**
required to make a new release

r? @rust-embedded/cortex-m (anyone)

### CODE REVIEW

**Comment by japaric** [comment]
Published: https://crates.io/crates/cortex-m-rt/0.6.2

**Comment by therealprof** [comment]
@japaric In retrospective we probably should have bumped the `cortex-m-rt-macros` version, too. I'm seeing annoying build problems most likely due to 0.1.0 being cached somewhere.

**Comment by japaric** [comment]
Oh, I'm dumb. This isn't fixed until we publish cortex-m-rt-macros v0.1.1 since that's were the fix is.

**Pull request merged**
