### PR TITLE
fix #74

### LINKED ISSUE #74: LLVM error on High Sierra
Building `cortex-m-rt` on `nightly`, `beta` and `stable` in Mac OS High Sierra (tested on two machines) results in the following error:

```
LLVM ERROR: Global variable '__RESET_VECTOR' has an invalid section specifier '.vector_table.reset_vector': mach-o section specifier requires a segment whose length is between 1 and 16 characters.
```

It build correctly on my Ubuntu 18.04 machine.

### PR DESCRIPTION
**Pull request by spookyvision**
special-cased linker section names to satisfy macos linker constraints

### CODE REVIEW

**Comment by jonas-schievink** [comment]
If you rebase this on current master CI should pass. We should also add a new job here that just build without `--target`, since that should work after this PR:

https://github.com/rust-embedded/cortex-m-rt/blob/89bdd8c7f80bf3614978f568284577f9ebdeb8ba/.github/workflows/ci.yml#L80

**Comment by spookyvision** [comment]
> If you rebase this on current master CI should pass. 

unfortunately not, still getting `language item required, but not found: 'eh_personality'`. Adding `panic = "abort"` to `[profile.dev]` made this go away (and unearthed another broken link section name, which I've fixed with another commit in the meantime), but this is probably not the right way to go ahead?

with the temporary fix for `eh_personality`, remaining errors are:

```
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-m64" "-arch" "x86_64" "-L" "/Users/anatol.ulrich/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib" "/Users/anatol.ulrich/work/cortex-m-rt/target/debug/examples/pre_init.41pb4842pbk6h8fj.rcgu.o" "-o" "/Users/anatol.ulrich/work/cortex-m-rt/target/debug/examples/pre_init" "-Wl,-dead_strip" "-nodefaultlibs" "-L" "/Users/anatol.ulrich/work/cortex-m-rt/target/debug/deps" "-L" "/Users/anatol.ulrich/work/cortex-m-rt/target/debug/build/cortex-m-rt-16e34855d1ab5756/out" "-L" "/Users/anatol.ulrich/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib" "/Users/anatol.ulrich/work/cortex-m-rt/target/debug/deps/libpanic_halt-fa926b5489e34768.rlib" "/Users/anatol.ulrich/work/cortex-m-rt/target/debug/deps/libcortex_m_rt-9ecd0db86bd21c1b.rlib" "/Users/anatol.ulrich/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/librustc_std_workspace_core-99bca6ace58141c5.rlib" "/Users/anatol.ulrich/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libcore-72a66f4c97a4c0c8.rlib" "/Users/anatol.ulrich/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libcompiler_builtins-e7cd9f0beed2fc0f.rlib"
  = note: ld: dynamic main executables must link with libSystem.dylib for architecture x86_64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

(several occurrences)

and

```
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-m64" "-arch" "x86_64" "-L" "/Users/anatol.ulrich/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib" "/Users/anatol.ulrich/work/cortex-m-rt/target/debug/examples/qemu.131k0j0eiyyppm1j.rcgu.o" "/Users/anatol.ulrich/work/cortex-m-rt/target/debug/examples/qemu.1856riucyqnr98i3.rcgu.o" "/Users/anatol.ulrich/work/cortex-m-rt/target/debug/examples/qemu.1kfksmat7ftapeni.rcgu.o" "/Users/anatol.ulrich/work/cortex-m-rt/target/debug/examples/qemu.2665blsxk9zbeyyd.rcgu.o" "/Users/anatol.ulrich/work/cortex-m-rt/target/debug/examples/qemu.2jskah2k0tfezcd0.rcgu.o" "/Users/anatol.ulrich/work/cortex-m-rt/target/debug/examples/qemu.3kpzafbr7npkpxbu.rcgu.o" "-o" "/Users/anatol.ulrich/work/cortex-m-rt/target/debug/examples/qemu" "-Wl,-dead_strip" "-nodefaultlibs" "-L" "/Users/anatol.ulrich/work/cortex-m-rt/target/debug/deps" "-L" "/Users/anatol.ulrich/work/cortex-m-rt/target/debug/build/cortex-m-rt-16e34855d1ab5756/out" "-L" "/Users/anatol.ulrich/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib" "/Users/anatol.ulrich/work/cortex-m-rt/target/debug/deps/libpanic_halt-fa926b5489e34768.rlib" "/Users/anatol.ulrich/work/cortex-m-rt/target/debug/deps/libcortex_m_semihosting-3fdbe42e3865b53f.rlib" "/Users/anatol.ulrich/work/cortex-m-rt/target/debug/deps/libcortex_m_rt-9ecd0db86bd21c1b.rlib" "/Users/anatol.ulrich/work/cortex-m-rt/target/debug/deps/libcortex_m-31c5941f301e80db.rlib" "/Users/anatol.ulrich/work/cortex-m-rt/target/debug/deps/libembedded_hal-c1582eeb3909021d.rlib" "/Users/anatol.ulrich/work/cortex-m-rt/target/debug/deps/libvoid-da898260d610f50d.rlib" "/Users/anatol.ulrich/work/cortex-m-rt/target/debug/deps/libnb-8d47a613bc85f978.rlib" "/Users/anatol.ulrich/work/cortex-m-rt/target/debug/deps/libnb-4367aac38fcdfd15.rlib" "/Users/anatol.ulrich/work/cortex-m-rt/target/debug/deps/libvolatile_register-a6bee15977cbed10.rlib" "/Users/anatol.ulrich/work/cortex-m-rt/target/debug/deps/libvcell-d9c3ff73f19dce6e.rlib" "/Users/anatol.ulrich/work/cortex-m-rt/target/debug/deps/libbare_metal-130812a6caf1a5da.rlib" "/Users/anatol.ulrich/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/librustc_std_workspace_core-99bca6ace58141c5.rlib" "/Users/anatol.ulrich/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libcore-72a66f4c97a4c0c8.rlib" "/Users/anatol.ulrich/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libcompiler_builtins-e7cd9f0beed2fc0f.rlib"
  = note: Undefined symbols for architecture x86_64:
            "_memcpy", referenced from:
                core::fmt::Write::write_fmt::h2ba7f7f38cfa5045 in libcortex_m_semihosting-3fdbe42e3865b53f.rlib(cortex_m_semihosting-3fdbe42e3865b53f.cortex_m_semihosting.2d5joapa-cgu.0.rcgu.o)
                _$LT$$RF$mut$u20$W$u20$as$u20$core..fmt..Write$GT$::write_fmt::h5c55410df270d15d in libcortex_m_semihosting-3fdbe42e3865b53f.rlib(cortex_m_semihosting-3fdbe42e3865b53f.cortex_m_semihosting.2d5joapa-cgu.0.rcgu.o)
            "_memset", referenced from:
                core::fmt::Write::write_char::hc0a51b72bc1ae45b in libcortex_m_semihosting-3fdbe42e3865b53f.rlib(cortex_m_semihosting-3fdbe42e3865b53f.cortex_m_semihosting.2d5joapa-cgu.0.rcgu.o)
            "___nop", referenced from:
                cortex_m::asm::nop::h74dc3ed233ca0d95 in qemu.2665blsxk9zbeyyd.rcgu.o
          ld: symbol(s) not found for architecture x86_64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by jonas-schievink** [comment]
Oh, the examples won't build even on Linux. We should only test that the main `cortex-m-rt` crate builds (not links).

**Review by jonas-schievink — APPROVED** [review]
bors r+

**Pull request merged**
