### PR TITLE
attributes: turn panics into compile errors

### PR DESCRIPTION
**Pull request by japaric**
Sample error messages:

```
error: `#[entry]` function must have signature `[unsafe] fn() -> !`
  --> examples/error.rs:15:1
   |
15 | fn main() {
   | ^^

error: aborting due to previous error
```

```
error: This attribute accepts no arguments
  --> examples/error.rs:14:1
   |
14 | #[entry(hello)]
   | ^^^^^^^^^^^^^^^

error: aborting due to previous error
```

```
error: This is not a valid exception name
  --> examples/error.rs:20:4
   |
20 | fn foo() {}
   |    ^^^

error: aborting due to previous error
```

### CODE REVIEW

**Comment by japaric** [comment]
Latest commit should fix the test suite on x86_64

**Comment by therealprof** [comment]
bors retry

**Comment by therealprof** [comment]
bors retry

**Pull request merged**
