### PR TITLE
Add thumbv8m.main support.

### PR DESCRIPTION
**Pull request by thejpster**
* Add thumbv8m.main support.
* Also adds feature flags into build.rs so SecureFault gets included.

### CODE REVIEW

**Comment by thejpster** [comment]
Ok, so there are two issues:

1) There's some overlap with #167. That's fine, I can re-base.
2) I have no idea how many Interrupt Vectors to set as the maximum when building for a non-Cortex-M target (which we do why?)

**Comment by therealprof** [comment]
@thejpster previously we just used the same number as for non-armv6m. But the explicit `panic!` also doesn't help a bit... ;)

**Comment by adamgreig** [comment]
Hopefully this (or #167, however that works out) can be merged once #183 is done.

**Comment by adamgreig** [comment]
bors try

**Comment by adamgreig** [comment]
@thejpster looks like you have some more-useful errors to investigate now ;)

**Comment by thejpster** [comment]
Builds are now green.

**Pull request merged**
