### PR TITLE
v0.5.2

### PR DESCRIPTION
**Pull request by japaric**
changes required for a new release

this commit also simplifies the examples by removing the exception handler overrides and adds an
example that overrides the exception handlers.

r? @adamgreig (chosen at random)

### CODE REVIEW

**Comment by korken89** [comment]
Thanks, no issue then.

**Comment by korken89** [comment]
I agree with @adamgreig on this

**Comment by korken89** [comment]
`__pre_init` (PR #81 ) has landed, hence I nominate that we include it.

**Comment by adamgreig** [comment]
I've updated the release branch to include the latest changes and updated the changelog accordingly.

r? @korken89

**Comment by korken89** [comment]
LGTM as well

**Comment by therealprof** [comment]
@adamgreig Are you going to publish this? Or shall I?

**Comment by adamgreig** [comment]
@therealprof Go ahead.

**Comment by therealprof** [comment]
@japaric Have you created the git tags manually or is there a secret function that does this automatically?

**Comment by adamgreig** [comment]
@therealprof I believe they're manual (I did them manually for the recent cortex-m and cortex-m-quickstart); see https://github.com/rust-embedded/wg/blob/master/ops/publish.md too.

**Comment by therealprof** [comment]
@adamgreig Weird, `cargo publish` yields ```error: received 404 not found response code```. Need to check my crates.io standing I guess.

**Comment by adamgreig** [comment]
Weird, are you logged in to crates.io via github? The whole cortex-m team is set as the owner so...

**Comment by therealprof** [comment]
Sure am. Maybe the team stuff is messed up? If I click on the Owner symbol in the crate I get a nice box saying: ```Team 'github:rust-embedded:cortex-m' does not exist```.

**Comment by adamgreig** [comment]
I get that same missing-team error on the cortex-m crate (which has the same owner), but I was able to push a release there successfully anyway. I think the crates.io github teams support might still be somewhat introductory.

Want me to try publishing it, or wait and see if @japaric can shed some light on the situation?

**Comment by therealprof** [comment]
Please go ahead. Plenty of chances to test this out I guess. ;)

**Comment by adamgreig** [comment]
No luck; same error as you.

**Comment by adamgreig** [comment]
...and we're back, and published.

**Pull request merged**
