### PR TITLE
Discard .ARM.exidx, closes #197

### LINKED ISSUE #197: .ARM.exidx may need to be ignored in LLD9
Context in https://github.com/rust-lang/rust/issues/62781.

Testing locally, adding a discard for `*(.ARM.exidx);` will prevent this error, or changing https://github.com/rust-embedded/cortex-m-rt/blob/master/link.x.in#L152 to `*(.ARM.exidx*);` both prevent linker errors. I am not sure which one is more idiomatic.

### PR DESCRIPTION
**Pull request by adamgreig**

### CODE REVIEW

**Comment by hannobraun** [comment]
> @bors r+

I think that needs to be `bors r+` (without the `@`).

**Comment by little-arhat** [comment]
I see that it's included in 0.6.10, but I only see 0.6.9 on crates.io. When fixed version will be released?

**Comment by therealprof** [comment]
@little-arhat Sorry, someone forgot to publish; try again now.

**Comment by little-arhat** [comment]
@therealprof no worries, thanks for fixing this!

**Pull request merged**
