### PR TITLE
[do not merge] Fixing the Travis build

### PR DESCRIPTION
**Pull request by korken89**
The travis build is failing on nightly, probably the old cortex-m dependency that's the issue.

### CODE REVIEW

**Comment by korken89** [comment]
1. It seems to be that the overflowing examples fail (as they should) but the `!` does not make the fail a pass in the script. Does anyone know why this is happening?
2. The final error is referring to `rust-lld: error while loading shared libraries: libLLVM-7.so: cannot open shared object file: No such file or directory`, but I am unable to replicate this on my local machine. Any ideas?

cc @rust-embedded/cortex-m

**Comment by japaric** [comment]
(2) is due to rust-lang/rust#53813. It will be fixed in tomorrow's nightly. The workaround is to install the `llvm-tools-preview` component or to roll back to a 2-days old nightly.

**Comment by korken89** [comment]
Thanks for the clarification!

**Comment by japaric** [comment]
Restarted the CI build and [it passed](https://travis-ci.org/rust-embedded/cortex-m-rt/builds/423038406?utm_source=github_status&utm_medium=notification) so I'm going to close this.

**Comment by korken89** [comment]
Thanks @japaric !

**Pull request closed without merging**
